# Generated by Django 5.2 on 2025-04-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category_product_digital_product_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='mproduct',
        ),
    ]
